# Generated by Django 2.0.1 on 2018-09-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_auto_20180913_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinfo',
            name='intro_text',
            field=models.CharField(default='DEFAULTintrotext', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='project_five',
            field=models.CharField(default='DEFAULTp5', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='project_four',
            field=models.CharField(default='DEFAULTp4', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='project_one',
            field=models.CharField(default='DEFAULTp1', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='project_seven',
            field=models.CharField(default='DEFAULTp7', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='project_six',
            field=models.CharField(default='DEFAULTp6', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='project_three',
            field=models.CharField(default='DEFAULTp3', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='project_two',
            field=models.CharField(default='DEFAULTp2', max_length=250),
        ),
    ]
